name: aws-v5
on:
  push:
    branches:
      - feat/beanstalk

jobs:
  build:
    runs-on: ubuntu-latest # 최초 ubuntu를 설치
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: make env.properties
        if: |
          contains(github.ref, 'main') ||
          contains(github.ref, 'dev')  ||
          contains(github.ref, 'feat')
        run: |
          touch env.properties
          echo "${{ secrets.ENV_PROPERTIES }}" > env.properties
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build # 빌드

      # UTC가 기준이기 때문에 한국시간으로 맞추려면 +9시간 해야 한다.
      - name: Get current time
        uses: 1466587594/get-current-time@v2 # 타임존 설정
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00" # 시간 확인

      - name: Show Current Time
        run: echo "CurrentTime=${{steps.current-time.outputs.formattedTime}}" # 시간 표시
      - name: Generate deployment package
        run: |
          mkdir -p deploy
          cp build/libs/*.jar deploy/application.jar
          cp Procfile deploy/Procfile
          cp -r .ebextensions deploy/.ebextensions
          cp -r .platform deploy/.platform
          cd deploy && zip -r deploy.zip .

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21 # 엘라스틱 빈스톡 환경 사용
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }} # 중괄호 2개는 깃헙 환경변수 접근
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: moit # 엘리스틱 빈스톡 애플리케이션 이름!
          environment_name: Moit-env-3 # 엘리스틱 빈스톡 환경 이름!
          version_label: github-action-${{steps.current-time.outputs.formattedTime}}
          region: ap-northeast-2 # 서울 서버로 압축파일을 전달해줌
          deployment_package: deploy/deploy.zip
          wait_for_environment_recovery: 60  # 배포 후 환경 복구 대기 시간